(function(e){e.execute(function(){e.when("A","ready").register("more-items-placeholder",function(b){var c=function(a,d){var c=this;this.$placeholder=a.find("."+d+"-more-items-placeholder");this.$grid=a.find("."+d+"-grid");this.$items=this.$grid.find("."+d+"-grid-item");this.$overflowItemCount=this.$placeholder.find("."+d+"-more-items-count");this.itemCount=this.$items.size();this.lastOverflowItemCount=0;this.$placeholder.remove();this.itemCount&&(this.refresh(),b.on.resize(function(){c.refresh()}))};
c.prototype.refresh=function(){var a=this.getOverflowItemCount();if(a!==this.lastOverflowItemCount)this.$placeholder.remove(),a>0&&(this.$overflowItemCount.text(a+1),this.$items.eq(this.itemCount-a-1).prepend(this.$placeholder),this.$placeholder.show()),this.lastOverflowItemCount=a};c.prototype.getOverflowItemCount=function(){var a=this.$grid.offset().top,d=this.$grid.height();return b.reduce(this.$items.get(),function(c,h){var f=b.$(h).offset().top-a;return c+(f>=d?1:0)},0)};return c});e.when("A",
"more-items-placeholder","ready").execute(function(b,c){b.$(".multi-item-multi-row").each(function(){new c(b.$(this),"multi-item-multi-row")});b.$(".multi-item-single-row").each(function(){new c(b.$(this),"multi-item-single-row")})})})})(function(){var e=window.AmazonUIPageJS||P,b=e.attributeErrors;return b?b("YourAccountMultiItemLayoutAssets"):e}());
(function(e){e.execute(function(){e.when("A").register("amzl-form-validator",function(b){function c(a){this.$form=b.$(a);this.requiredInputNames=this.getRequiredInputNames()}c.prototype.hasRequiredValues=function(){var a=this.getFormData();return b.$.grep(this.requiredInputNames,function(d){return b.trim(a[d]||"").length===0}).length===0};c.prototype.isValid=function(){return this.hasRequiredValues()};c.prototype.getRequiredInputNames=function(){return this.$form.find(".js-flag-required:visible, input[type=hidden].js-flag-required").map(function(){var a=
b.$(this);return a.attr("name")||a.find("input, select").attr("name")||a.siblings("input, select").attr("name")}).get()};c.prototype.getFormData=function(){var a=this.$form.serializeArray(),d={};b.each(a,function(a){d[a.name]=a.value});return d};return c});e.when("A","button-with-disabled-message","amzl-form-validator").register("amzl-form",function(b,c,a){var d=function(a){a.find(".amzl-error-message").removeClass("aok-hidden")},g=function(a,d){var c=d.isEnabled();a&&!c?d.enable():!a&&c&&d.disable()},
h=function(d,h,f){var d=b.$(d),e=d.find(".amzl-submit-button.hide-if-no-js"),k,l;d.size()&&e.size()&&(f&&e.val(f),k=new c(e,h||e.find("input").data("disabled_message")),l=new a(d),g(l.isValid(),k),d.undelegate(".validate").delegate("input, select","change.validate keyup.validate keydown.validate keypress.validate",function(){g(l.isValid(),k)}))},f=function(a){var d=b.$(a),c=d.find(".amzl-action-container"),g=d.find(".amzl-error-message");c.size()&&d.delegate(".amzl-action-container-handle","change",
function(a){var a=b.$(a.target),i=a.val(),f=a.closest(".a-radio").data();a.is(":checked")&&(a.closest(".amzl-action-container-handle").addClass("amzl-action-container-handle--selected").siblings(".amzl-action-container-handle").removeClass("amzl-action-container-handle--selected"),c.addClass("aok-hidden").filter(".amzl-action-container-"+i).removeClass("aok-hidden"),h(d,f.instructionstext,f.submittext),g.addClass("aok-hidden"))})};b.declarative("amzl-action-form","submit",function(a){var c=a.$target.closest("form"),
g=c.attr("action"),h=c.attr("method"),f=c.serialize();b.ajax(g+"?"+f,{method:h,success:function(a){a&&a.status==="success"?window.location.href=c.find("input[name=successUrl]").val():d(c)},error:function(){d(c)}});a.$event.preventDefault()});return function(a){a=b.$(a);a.size()&&(h(a),f(a))}});e.when("A","amzl-form","ready").execute(function(b,c){c(b.$(".amzl-action-form"))});e.when("A","a-modal","amzl-form").register("amzl-modal",function(b,c,a){b.on("a:popover:ajaxContentLoaded:amzl-modal",function(d){a(d.popover.$container.find(".amzl-action-form"))});
return function(a,g,h){var f=g.url;g.get&&(f+=f.indexOf("?")===-1?"?":"&",f+=b.$.param(g.get));c.create(a,{name:"amzl-modal",header:g.title,url:f,width:h||500}).show()}});e.when("A","a-dropdown","amzl-modal","ready").execute(function(b,c,a){b.declarative("amzl-actions-dropdown","change",function(d){var b=d.$target,h=b.val();h&&(d=d.data[h],h=d.declarativeAction&&d.declarativeAction.action_params||{},a(b.find("option:selected"),d,h.modalWidth),c.getSelect(b).setValue(""))})});e.when("A","amzl-modal",
"ready").execute(function(b,c){b.declarative("amzl-actions-link","click",function(a){var d=a.$target;c(d,{title:d.text(),url:d.attr("href")},a.data.modalWidth);a.$event.preventDefault()})});e.when("A","ready").execute(function(b){b.on("a:button-group:amzl-reschedule-date-picker:toggle",function(c){c=c.selectedButton.$button.closest(".simple-date-picker__date").data("epoch");b.$(".amzl-reschedule-date-input").val(c).trigger("change")})});e.when("A","a-button","a-tooltip").register("button-with-disabled-message",
function(b,c,a){function d(a,d){this.$button=b.$(a);this.auiButton=c(this.$button);this.disabledMessage=d;this.auiButton.isEnabled()||this.disable()}d.prototype.disable=function(){this.auiButton.disable();a.remove(this.$button);a.create(this.$button,{content:this.disabledMessage});return this};d.prototype.enable=function(){this.auiButton.enable();a.remove(this.$button);return this};d.prototype.isEnabled=function(){return this.auiButton.isEnabled()};return d})})})(function(){var e=window.AmazonUIPageJS||
P,b=e.attributeErrors;return b?b("YourAccountOrderCareAmzlAssets"):e}());
(function(e){e.execute(function(){e.when("A","ready").register("logger",function(){return{log:function(a){a="YourAccountShipTrack_"+a;window.ue&&typeof window.ue.count==="function"&&window.ue.count(a,(window.ue.count(a)||0)+1);typeof window.uex==="function"&&window.uex("ld",a,{wb:1})}}});var b=function(a){var d,c,b,f;if(a.length)a.css({visibility:"hidden",display:"block"}),d=a.outerHeight(!1),c=a.outerWidth(!1),b=a.position().left,f=a.position().top,a.css({visibility:"visible",display:"none"});return{height:d,
width:c,left:b,top:f}},c=function(a,d,c){this.$element1=a;this.$element2=d;this.spacer=typeof c==="undefined"?5:c;return this};c.prototype.getElementCoordinates=function(a){if(!a.length)return!1;var d=a.offset(),c=a.outerHeight(),h=a.outerWidth();if(!a.is(":visible"))d=a.show().offset(),a.hide(),a=b(a),c=a.height,h=a.width;return{height:c,width:h,left:d.left,right:d.left+h,top:d.top,bottom:d.top+c}};c.prototype.getPositions=function(a){var d=this.getElementCoordinates(a),c,b,f,i,j=a.data("future-state");
j&&(i=a.parent().offset(),c=j["margin-top"],b=j["margin-left"],f=typeof j.left!=="undefined"?j.left+i.left:void 0,i=typeof j.top!=="undefined"?j.top+i.top:void 0);f=typeof f!=="undefined"?parseInt(f,10):d.left;f+=typeof b!=="undefined"?parseInt(b,10):0;b=typeof i!=="undefined"?parseInt(i,10):d.top;b+=typeof c!=="undefined"?parseInt(c,10):0;return[[f,f+d.width],[b,b+d.height]]};c.prototype.willOverlap=function(){if(!this.$element1.length||!this.$element2.length||this.$element1.get(0).parentNode!==
this.$element2.get(0).parentNode)return!1;var a=this.getMarginDiffs();return a.left!==0&&a.right!==0&&a.top!==0&&a.bottom!==0};c.prototype.getMarginDiffs=function(){var a,d,c,b,f={left:0,right:0,top:0,bottom:0},i=this.spacer;b=this.getPositions(this.$element1);var j=this.getPositions(this.$element2);a=j[0][1]-b[0][0];d=j[0][0]-b[0][1];c=j[1][1]-b[1][0];b=j[1][0]-b[1][1];f.left=a>i?Math.max(i,a+i):0;f.right=d<i?Math.min(-i,d-i):0;f.top=c>i?Math.max(i,c+i):0;f.bottom=b<i?Math.min(-i,b-i):0;return f};
e.when("A","ready").register("widget-shared",function(a){var d=function(){this.shortAnimationTime=400;this.longAnimationTime=1E3;this.animationEase="ease"};d.prototype.Overlaps=c;d.prototype.getHiddenElementDimensions=b;d.prototype.stAnimate=function(d,c,b,i){if(d&&d.length){var b=b||this.shortAnimationTime,i=i||this.animationEase,j=d.data("future-state")||{},e;for(e in c)e&&(j[e]=c[e]);d.data("future-state",j);a.animate(d,c,b,i,function(){a.isAnimated(d)||d.removeData("future-state")})}};return d})})})(function(){var e=
window.AmazonUIPageJS||P,b=e.attributeErrors;return b?b("YourAccountShipTrackWidgetAssets"):e}());
(function(e){e.execute(function(){e.when("A","a-modal","wmp-v2-constants").execute(function(b,c,a){b.declarative(a.MODAL_NAME,"click",function(d){var g=c.get(a.MODAL_NAME);g&&g.isActive()?g.hide().update({header:d.data.header,url:d.data.url}).show():(c.remove(a.MODAL_NAME),c.create(b.$("<div />"),{activate:"onclick",cache:!1,dataStrategy:"ajax",header:d.data.header,name:a.MODAL_NAME,url:d.data.url,width:a.MODAL_WIDTH}).show())})});e.when("A","wmp-submit-request","wmp-v2-constants","wmp-v2-common",
"ready").execute(function(b,c,a,d){b.declarative("wmp-v2-refund-replace-submit","click",function(g){g.$event.preventDefault();d.hideMessage();var h=b.$(a.PRE_SUBMIT_VIEW_CLASS).find("input[name="+a.REFUND_REPLACE_OPTION_NAME+"]:radio:checked").val(),f=a.ERROR_MESSAGE_ID;if(h===a.REFUND_OPTION_VALUE)f=a.REFUND_SUCCESS_MESSAGE_ID;else if(h===a.REPLACE_OPTION_VALUE)f=a.REPLACE_SUCCESS_MESSAGE_ID;g.data.requestSuccessOverride==="1"?d.showMessage(g.data.submitMessageUrl,f):c(h,g.data.submitParams).done(function(){d.showMessage(g.data.submitMessageUrl,
f)}).fail(function(){d.showMessage(g.data.submitMessageUrl,a.ERROR_MESSAGE_ID)})});b.declarative("wmp-v2-refund-submit","click",function(b){b.$event.preventDefault();d.hideMessage();b.data.requestSuccessOverride==="1"?d.showMessage(b.data.submitMessageUrl,a.REFUND_SUCCESS_MESSAGE_ID):c(a.REFUND_OPTION_VALUE,b.data.submitParams).done(function(){d.showMessage(b.data.submitMessageUrl,a.REFUND_SUCCESS_MESSAGE_ID)}).fail(function(){d.showMessage(b.data.submitMessageUrl,a.ERROR_MESSAGE_ID)})});b.declarative("wmp-v2-replace-submit",
"click",function(b){b.$event.preventDefault();d.hideMessage();b.data.requestSuccessOverride==="1"?d.showMessage(b.data.submitMessageUrl,a.REPLACE_SUCCESS_MESSAGE_ID):c(a.REPLACE_OPTION_VALUE,b.data.submitParams).done(function(){d.showMessage(b.data.submitMessageUrl,a.REPLACE_SUCCESS_MESSAGE_ID)}).fail(function(){d.showMessage(b.data.submitMessageUrl,a.ERROR_MESSAGE_ID)})})});e.when("A","wmp-v2-constants","ready").register("wmp-v2-common",function(b,c){return{hideMessage:function(){b.$("."+c.ERROR_MESSAGE_CLASS).addClass(c.AUI_HIDDEN_CLASS)},
showMessage:function(a,d){var g=b.$("."+c.ERROR_MESSAGE_CLASS);d===c.ERROR_MESSAGE_ID&&g.size()?g.removeClass(c.AUI_HIDDEN_CLASS):window.location.href=a.indexOf("?")!==-1?a+"&"+c.MESSAGE_ID_URL_PARAM+"="+d:a+"?"+c.MESSAGE_ID_URL_PARAM+"="+d}}});e.when("A","wmp-common-constants").register("wmp-v2-constants",function(b,c){var a={};b.map(c,function(d,c){a[c]=d});b.map({PRE_SUBMIT_VIEW_CLASS:".wmp-v2-refund-replace-pre-submit",MESSAGE_ID_URL_PARAM:"wmpMessageId",ERROR_MESSAGE_ID:"1",REFUND_SUCCESS_MESSAGE_ID:"2",
REPLACE_SUCCESS_MESSAGE_ID:"3",ERROR_MESSAGE_CLASS:"wmp-error-message",AUI_HIDDEN_CLASS:"aok-hidden",MODAL_NAME:"wheres-my-package-modal",MODAL_WIDTH:520},function(d,c){a[c]=d});return a});e.when("A").register("wmp-common-constants",function(){return{REFUND_REPLACE_OPTION_NAME:"wmp_option",REFUND_OPTION_VALUE:"Refund",REPLACE_OPTION_VALUE:"Replacement"}});e.when("A").register("wmp-submit-request",function(b){return function(c,a){var d=new b.$.Deferred;a.option=c;b.ajax("/gp/shared-cs/ajax/wmp/submitter.html",
{method:"post",dataType:"json",params:a,timeout:5E3,cache:!1,contentType:"application/x-www-form-urlencoded; charset=utf-8",success:function(a){1===a.success?d.resolve():d.reject()},error:function(){d.reject()}});return d.promise()}});e.when("A").register("wmp-find-pop-cmpt",function(){return function(b,c){var a=b.parents(".a-popover").data("a-popover-id");return c.get(a)}});e.when("A","wmp-find-pop-cmpt").register("wmp-hide-pop-cmpt",function(b,c){return function(a,d){var b=c(a,d);b&&"function"===
typeof b.hide&&b.hide()}});e.when("A","a-modal","ready").execute(function(b,c){var a=b.$;a(document).delegate("#scfiModalDismiss","click",function(a){c.get("scfiButton_modal").hide();a.preventDefault()})});e.when("A","wmp-common-constants").register("wmp-popover-constants",function(b,c){var a={};b.map(c,function(d,c){a[c]=d});b.map({INTRO_VIEW_CLASS:"wmp-step-intro",PRE_SUBMIT_VIEW_CLASS:"wmp-popover-step-pre-submit",WAIT_VIEW_CLASS:"wmp-popover-step-waiting",REFUND_SUCCESS_VIEW_CLASS:"wmp-popover-step-refund-success",
REPLACE_SUCCESS_VIEW_CLASS:"wmp-popover-step-replace-success",ERROR_VIEW_CLASS:"wmp-popover-step-error"},function(d,c){a[c]=d});return a});e.when("A","ready").register("wmp-popover-common",function(){function b(c,a){var d=c.parents("."+a);d.length<1&&(d=c.parents(".a-popover").find("."+a));return d}return{getView:b,switchViews:function(c,a,d){c=b(c,a);d=c.siblings("."+d);c.hide();d.show()}}});e.when("A","wmp-popover-constants","wmp-popover-common","ready").execute(function(b,c,a){function d(d){d.$event.preventDefault();
a.switchViews(d.$target,c.INTRO_VIEW_CLASS,c.PRE_SUBMIT_VIEW_CLASS)}b.declarative("wmp-popover-init-refund-replace","click",d);b.declarative("wmp-popover-init-refund","click",d);b.declarative("wmp-popover-init-replace","click",d)});e.when("A","wmp-submit-request","wmp-popover-constants","wmp-popover-common","ready").execute(function(b,c,a,d){b.declarative("wmp-popover-submit-refund-replace","click",function(b){b.$event.preventDefault();var h=d.getView(b.$target,a.PRE_SUBMIT_VIEW_CLASS).find("input[name="+
a.REFUND_REPLACE_OPTION_NAME+"]:radio:checked").val();d.switchViews(b.$target,a.PRE_SUBMIT_VIEW_CLASS,a.WAIT_VIEW_CLASS);c(h,b.data.submitParams).done(function(){d.switchViews(b.$target,a.WAIT_VIEW_CLASS,h===a.REFUND_OPTION_VALUE?a.REFUND_SUCCESS_VIEW_CLASS:a.REPLACE_SUCCESS_VIEW_CLASS)}).fail(function(){d.switchViews(b.$target,a.WAIT_VIEW_CLASS,a.ERROR_VIEW_CLASS)})});b.declarative("wmp-popover-submit-refund","click",function(b){b.$event.preventDefault();d.switchViews(b.$target,a.PRE_SUBMIT_VIEW_CLASS,
a.WAIT_VIEW_CLASS);c(a.REFUND_OPTION_VALUE,b.data.submitParams).done(function(){d.switchViews(b.$target,a.WAIT_VIEW_CLASS,a.REFUND_SUCCESS_VIEW_CLASS)}).fail(function(){d.switchViews(b.$target,a.WAIT_VIEW_CLASS,a.ERROR_VIEW_CLASS)})});b.declarative("wmp-popover-submit-replace","click",function(b){b.$event.preventDefault();d.switchViews(b.$target,a.PRE_SUBMIT_VIEW_CLASS,a.WAIT_VIEW_CLASS);c(a.REPLACE_OPTION_VALUE,b.data.submitParams).done(function(){d.switchViews(b.$target,a.WAIT_VIEW_CLASS,a.REPLACE_SUCCESS_VIEW_CLASS)}).fail(function(){d.switchViews(b.$target,
a.WAIT_VIEW_CLASS,a.ERROR_VIEW_CLASS)})})});e.when("A","a-popover","wmp-hide-pop-cmpt").execute(function(b,c,a){b.declarative("wmp-popover-cancel","click",function(d){d.$event.preventDefault();a(d.$target,c)})});e.when("A","wmp-common-constants").register("wmp-expander-constants",function(b,c){var a={};b.map(c,function(d,c){a[c]=d});b.map({CONTENTS_CLASS:"wmp-expander-content",FALLBACK_VIEW_CLASS:"wmp-expander-step-fallback",WAIT_VIEW_CLASS:"wmp-expander-step-waiting",DATA_LOAD_PARAMS:"load-params",
DATA_IS_LOADED:"is-loaded",DATA_FOR_TPL_HEADING:"heading",WAITING_TPL_ID:"wmp-expander-template-waiting",REFUND_SUCCESS_TPL_ID:"wmp-expander-template-refund-success",REPLACE_SUCCESS_TPL_ID:"wmp-expander-template-replace-success",ERROR_TPL_ID:"wmp-expander-template-error"},function(d,c){a[c]=d});return a});e.when("A","wmp-expander-constants","ready").execute(function(b,c){function a(a){var c=new b.$.Deferred;b.ajax("/gp/shared-cs/wmp/ajax-handler/expander-contents",{method:"get",dataType:"html",params:a,
timeout:5E3,cache:!1,contentType:"text/html; charset=utf-8",success:function(a){c.resolve(a)},error:function(){c.reject()}});return c.promise()}b.on("a:expander:wheres_my_package:toggle:expand",function(d){var b=d.expander.$expander;if(!b.data(c.DATA_IS_LOADED)){var d=b.data(c.DATA_LOAD_PARAMS),h=b.find("."+c.CONTENTS_CLASS),f=b.find("."+c.FALLBACK_VIEW_CLASS),i=b.find("."+c.WAIT_VIEW_CLASS);f.hide();i.show();a(d).done(function(a){i.hide();h.append(a);b.data(c.DATA_IS_LOADED,1)}).fail(function(){i.hide();
f.show()})}})});e.when("A","a-modal","wmp-hide-pop-cmpt").execute(function(b,c,a){b.declarative("wmp-expander-cancel","click",function(d){d.$event.preventDefault();a(d.$target,c)})});e.when("A","wmp-expander-constants","ready").register("wmp-expander-templates",function(b,c){var a={};b.each([c.WAITING_TPL_ID,c.REFUND_SUCCESS_TPL_ID,c.REPLACE_SUCCESS_TPL_ID,c.ERROR_TPL_ID],function(d){var g=b.$("#"+d),h=g.data(c.DATA_FOR_TPL_HEADING),g=g.html();a[d]={header:h,content:g,footer:""}});return{fetch:function(d){return a[d]}}});
e.when("A","a-modal","wmp-find-pop-cmpt","wmp-expander-constants","wmp-expander-templates","wmp-submit-request").execute(function(b,c,a,d,g,h){function f(a,d){var c=g.fetch(d);a.update(c)}b.declarative("wmp-expander-submit-refund-replace","click",function(b){b.$event.preventDefault();var g=a(b.$target,c),e=g.getContent().find("input[name="+d.REFUND_REPLACE_OPTION_NAME+"]:radio:checked").val();f(g,d.WAITING_TPL_ID);h(e,b.data.submitParams).done(function(){f(g,e===d.REFUND_OPTION_VALUE?d.REFUND_SUCCESS_TPL_ID:
d.REPLACE_SUCCESS_TPL_ID)}).fail(function(){f(g,d.ERROR_TPL_ID)})});b.declarative("wmp-expander-submit-refund","click",function(b){b.$event.preventDefault();var g=a(b.$target,c);f(g,d.WAITING_TPL_ID);h(d.REFUND_OPTION_VALUE,b.data.submitParams).done(function(){f(g,d.REFUND_SUCCESS_TPL_ID)}).fail(function(){f(g,d.ERROR_TPL_ID)})});b.declarative("wmp-expander-submit-replace","click",function(b){b.$event.preventDefault();var g=a(b.$target,c);f(g,d.WAITING_TPL_ID);h(d.REPLACE_OPTION_VALUE,b.data.submitParams).done(function(){f(g,
d.REPLACE_SUCCESS_TPL_ID)}).fail(function(){f(g,d.ERROR_TPL_ID)})})})})})(function(){var e=window.AmazonUIPageJS||P,b=e.attributeErrors;return b?b("WheresMyPackageJS"):e}());
(function(e){e.execute(function(){e.when("A","a-modal").execute(function(b,c){b.declarative("close-archive-order-modal","click",function(a){a.$event.preventDefault();(a=c.get("archive-order-modal"))&&"function"===typeof a.hide&&a.hide()})});e.when("A").register("b2b-account-dropdown",function(b){function c(a){b.declarative(a,"change",function(a){var a=a.$target.context.form,c=b.$("#b2bDropdown"),h="/ref=b2b_yo_dd_",f=c.find("option:selected").val()||"unknown",i={yourself:"all",unknown:"unk"};h+=c.attr("name")===
"delegatedCustId"?"pd_"+(i[f]||"del"):f.substr(0,3).toLowerCase();a.action+=h;a.submit()})}c("b2b-account-change");return{assignAction:c}});e.when("A","jQuery").execute(function(b){b.declarative("remaining-customizations-action","click",function(c){c.$currentTarget.parent().find(".remaining_customization_info").show();c.$currentTarget.hide();c.$event.preventDefault()})});e.when("A").register("order-period-dropdown",function(b){function c(a){b.declarative(a,"change",function(a){a.$target.context.form.submit()})}
c("time-period-change");return{assignAction:c}});e.when("A","ready").register("popover-page-data",function(b){var c=b.state("initial-popover-data");return{getDefaultTimePeriodValue:function(){return c?c.defaultTimePeriodValue:void 0},getSelectedTimePeriodValue:function(){return c?c.selectedTimePeriodValue:void 0},isCancelled:function(){return c?c.isCancelled:void 0},isOpen:function(){return c?c.isOpen:void 0},isFresh:function(){return c?c.isFresh:void 0},getCancelledValue:function(){return c?c.cancelledValue:
"cancelled"},getOpenValue:function(){return c?c.openValue:"open"},getFreshValue:function(){return c?c.freshValue:"freshOrders"}}});e.when("A","popover-page-data","ready").register("filter-popover",function(b,c){var a=b.$("#timePeriodSection"),d=b.$("#orderFilterForm"),g=d.find("#digitalOrdersHidden"),h=d.find("#unifiedOrdersHidden"),f=d.find("#orderFilterHidden"),i=b.$("#orderFilterSection"),j;c.isCancelled()||c.isOpen()?(c.isCancelled()?f.attr("value",c.getCancelledValue()):f.attr("value",c.getOpenValue()),
j=c.getDefaultTimePeriodValue(),i.find('input[type="radio"][value="'+j+'"]').parent("label").find("i").addClass("a-icon-touch-radio-active"),a.hide()):(j=c.getSelectedTimePeriodValue()?c.getSelectedTimePeriodValue():c.getDefaultTimePeriodValue(),f.attr("value",j));b.declarative("popover-time-range-select","click",function(a){j=a.data.range;a=c.getFreshValue();a=typeof a!=="undefined"&&b.$("#filterTypeSection input:checked").closest(".yo-filters-radio-button").data("type")===a?a+"-"+j:j;f.attr("value",
a)});b.declarative("digital-or-physical-order-select","click",function(d){g.attr("value",d.data.digital);h.attr("value",d.data.unified);f.attr("value",j);a.slideDown("fast")});b.declarative("open-or-cancel-order-select","click",function(d){g.removeAttr("value");h.removeAttr("value");f.attr("value",d.data.filterType);a.slideUp("fast")});b.declarative("order-type-by-date-select","click",function(d){f.attr("value",d.data.filterType+"-"+j);a.slideDown("fast")});b.declarative("apply-OH-filter","click",
function(){d.submit()});return{getFilterLabel:function(){var a=b.$("#filterTypeSection input:checked").closest(".yo-filters-radio-button"),d=a.data("type"),a=a.data("label");return d==="open"||d==="cancelled"?a:(d=b.$("#timePeriodSection input:checked").closest(".yo-filters-radio-button"),d.data("range"),d=d.data("label"),a+", "+d)}}});e.when("A","ready").register("right-rail",function(b){function c(){var c=a(),b;a:{for(b in c)if(b&&c.hasOwnProperty(b)){var j=c[b];if(!j||j.length===0||j.width()===
0||j.height()===0){b=!1;break a}}b=!0}b&&(e=g.outerWidth(!0),n=h.outerWidth(!0),k=i+e+i,l=i+n+k,b=c.yourOrders.offset(),b=c.firstOrder.offset().top-b.top,c.rightRail.css({top:b+"px"}),d(c))}function a(){return{contentCenter:h,firstOrder:b.$(".order").first(),rightRail:g,yourOrders:f}}function d(a){var d;if(d=a.rightRail.children().length>0){d=b.$(window).width();var c=a.rightRail.is(":visible");d=d-l>(c?0:j)}var c=b.$(window).width(),g=c-n-k;d&&g<k?a.yourOrders.width(c-g*2):a.yourOrders.width(n);
d?a.rightRail.show():a.rightRail.hide()}var g=b.$("#rightRail"),h=b.$("#yourOrdersContent"),f=b.$("#yourOrders"),i=20,j=5,e,n,k,l;b.$(window).resize(function(){d(a())});c();return{initialize:c,remove:function(){g.empty().hide();f.width(n)}}});e.when("A").execute(function(b){b.on("a:popover:afterUpdatePosition:recipient",function(c){try{var a=c.popover,d=a.$popover,b=a.$trigger.find(".trigger-text"),h=b.offset().left+b.width()/2-d.width()/2,f={top:d.offset().top,left:h};d.offset(f)}catch(i){}})});
e.when("A","ready").register("ie-detect",function(b){function c(d,c){var h=b.$(c).length>0;a[d]=h}var a={};return{isIE6OrOlder:function(){a.IE6OrOlder===void 0&&c("IE6OrOlder",".a-lt-ie7");return a.IE6OrOlder},isIE7OrOlder:function(){a.IE7OrOlder===void 0&&c("IE7OrOlder",".a-lt-ie8");return a.IE7OrOlder},isIE8OrOlder:function(){a.IE8OrOlder===void 0&&c("IE8OrOlder",".a-lt-ie9");return a.IE8OrOlder},isIE9OrOlder:function(){a.IE9OrOlder===void 0&&c("IE9OrOlder",".a-lt-ie10");return a.IE9OrOlder}}});
e.when("A").register("track-package-dom-helper",function(b){return{findElements:function(c){c=c.parents(".shipment");return{shipmentEl:c,detailsEl:c.find(".tracking-details"),buttonEl:c.find(".track-package-button"),contentsEl:c.find(".tracking-details .contents"),hideEl:c.find(".tracking-details .hide")}},findParamsForPackagesFromTrackEl:function(c){return c.parent(".a-declarative").data("show-tracking-details")},removeTag:function(c,a){c=b.$(c);c=c.map(function(d,c){var h=b.$(c).prop("tagName");
return a.toUpperCase()===h?null:c});c.find(a.toLowerCase()).remove();return c},convertToDivs:function(c,a){var d=RegExp("<\\s*"+a.join("|<\\s*"),"gi"),g=RegExp("<\\s*\\/\\s*"+a.join("\\s*>|<\\s*\\/\\s*")+"\\s*>","gi"),c=b.$(c)[0];c.outerHTML=c.outerHTML.replace(d,"<div").replace(g,"</div>")}}});e.when("A","ie-detect").register("track-package-toggler",function(b,c){var a=!c.isIE9OrOlder();return{showDetails:function(d){a?(d.hideEl.hide(),b.slideDown(d.detailsEl,100,"ease-out",function(){d.hideEl.show()})):
d.detailsEl.show();d.buttonEl.css("visibility","hidden")},hideDetails:function(d){a?(d.hideEl.hide(),b.slideUp(d.detailsEl,100,"ease-out",function(){d.hideEl.show()})):d.detailsEl.hide();d.buttonEl.css("visibility","visible")}}});e.when("A").register("track-package-details-status",function(b){return{detailsLoadedOk:function(c){return b.$(c).data("trackDetailsLoaded")||!1},detailsLoadFailed:function(c){return!1===b.$(c).data("trackDetailsLoaded")},setIsLoaded:function(c,a){b.$(c).data("trackDetailsLoaded",
a)}}});e.when("A","track-package-dom-helper","ready").register("track-package-details-parser",function(b,c){var a=b.$("#trackPkgDetailsTemplate").html();b.$("#yourOrders, #orderDetails").delegate("a.reloader","click",function(a){a.preventDefault();window.location.reload()});return{parseResult:function(d,g){var h=b.$(d.html),f=h.find(".trackTable");h.find(".eyeHead").remove();h=c.removeTag(h,"script");g&&f.size()&&f.addClass("fauxTable").each(function(){c.convertToDivs(this,"table,tbody,thead,tfoot,th,tr,td".split(","))});
h.find("a").each(function(){var a=b.$(this);"#"===a.attr("href")&&!a.hasClass("reloader")&&a.attr("href",d.shipTrackPageUrl)});f=b.$(a);f.find("a.ship-track-link").attr("href",d.shipTrackPageUrl);f.find(".details").append(h);return f}}});e.when("A","track-package-details-status","track-package-details-parser","ready").register("track-package-details-loader",function(b,c,a){function d(a){var d=new b.$.Deferred;return{ajaxHandle:b.ajax("/gp/widgets/shiptrack/display-tracking-info.html",{method:"get",
dataType:"json",params:a.ajaxParams,timeout:1E4,cache:!1,success:function(c){c&&c.html?d.resolve({html:c.html,shipTrackPageUrl:a.shipTrackPageUrl}):d.reject()},error:function(){d.reject()}}),promise:d.promise()}}function g(a){var d=b.$(f);d.find("a.ship-track-link").attr("href",a);return d}var h=b.$("#trackPkgLoadingTemplate").html(),f=b.$("#trackPkgAjaxErrorTemplate").html();return{load:function(i,f){if(!b.objectIsEmpty(i)&&!c.detailsLoadedOk(f)){c.detailsLoadFailed(f)&&f.html(h);var e=[],n=b.map(i,
function(a){a=d(a);e.push(a.ajaxHandle);return a.promise});b.$.when.apply(b.$,n).done(function(){var d=Array.prototype.slice.call(arguments);f.empty();b.each(d,function(d){f.append(a.parseResult(d,i[0].useFauxTrackTable))});c.setIsLoaded(f,!0)}).fail(function(){b.each(e,function(a){a.abort()});f.html(g(i[0].shipTrackPageUrl));c.setIsLoaded(f,!1)})}}}});e.when("A","track-package-dom-helper","track-package-toggler","track-package-details-loader").execute(function(b,c,a,d){b.declarative("show-tracking-details",
"click",function(b){b.$event.preventDefault();var h=c.findElements(b.$target);a.showDetails(h);d.load(b.data,h.contentsEl)});b.declarative("hide-tracking-details","click",function(d){d.$event.preventDefault();d=c.findElements(d.$target);a.hideDetails(d)});b.declarative("retry-tracking-details","click",function(a){a.$event.preventDefault();var a=c.findElements(a.$target),b=c.findParamsForPackagesFromTrackEl(a.buttonEl);d.load(b,a.contentsEl)})});e.when("A","mash").register("aw-mash",function(b,c){return c});
e.when("A","a-modal").execute(function(b,c){function a(a){a.$event.preventDefault();a=a.$target.closest(".a-popover");(a=c.get(a))&&"function"===typeof a.hide&&a.hide()}b.declarative("reorder-modal-cancel","click",a);e.when("aw-mash","a-modal-factory").execute(function(d,c){function h(a){typeof amazon==="object"&&typeof window.amazon.mash==="object"&&typeof window.amazon.mash.navigate==="function"?window.amazon.mash.navigate({url:a}):window.location.assign(a)}b.declarative("reorder-modal-add-to-cart",
"click",function(d){b.declarative("reorder-modal-success-cart","click",function(d){a(d);h("/gp/cart/view.html")});b.declarative("reorder-modal-success-continue","click",a);b.declarative("reorder-modal-error-ok","click",a);(function(d){function f(c){b.ajax("/gp/aw/detail/ajax/add-to-cart/ref="+m,{method:"post",params:c.inputs,timeout:c.timeout,success:function(c){c&&c.ok?(a(d),q?n(c):(b.$("#reorderATCChangeover"+p).show(),setTimeout(function(){n(c)},1700))):e(l.ATCProblemText)},failure:function(){e(l.ATCProblemText)}})}
function e(){var a=b.$("<a></a>"),d=b.$("#reorderATCErrorModalFooter"+p),a=c.create(a,{header:l.failedATCText,footer:d.html(),inlineContent:l.ATCProblemText,dataStrategy:"inline"});a.refresh();a.show()}function n(a){a=parseInt(a.numActiveItemsInCart,10);window.amazon.mash.cart.didUpdate({newCartQuantity:a});if(q===0)h("/gp/cart/view.html");else{var a=b.$("<a></a>"),d=b.$("#reorderATCSuccessModal"+p),a=c.create(a,{header:l.itemAddedToCartText,inlineContent:d.html(),dataStrategy:"inline"});a.refresh();
a.show()}}var k=d.data,l=k.strings?k.strings:{},m=k.ref,p=k.suffix,q=k.doShowATCModal;k.requiresSignIn?window.amazon.mash.showLoginDialog({successCallback:function(){f(k)},failCallback:function(a){a!=="CANCELED"&&e(a)}}):f(k)})(d)})})});e.when("A","a-dropdown").execute(function(b,c){b.declarative("legal-invoice-download","change",function(a){var a=c.getSelect(a.$target),d=a.val();if(d!=="")window.location=d,a.setValue("")})});e.when("A","a-dropdown","a-modal","ready").execute(function(b,c){b.declarative("problem-button-dropdown",
"change",function(a){var a=a.$target,d=a.find("option:selected"),g=d.data("actionname"),h=d.data("url");c.getSelect(a).setValue("");if(g)b.trigger("a:declarative:"+g+":click",{data:{header:d.data("header")||"",url:h}});else if(h)window.location=h})})})})(function(){var e=window.AmazonUIPageJS||P,b=e.attributeErrors;return b?b("YourAccountOrderHistoryJS"):e}());